### ISSUE TITLE
Encrypted Data?

### ISSUE THREAD

**Issue by curran** [share/sharedb#585] opened 2023-01-06 19:42 UTC
Greetings,

I'm looking to solve the problem that server admins are able to access all data for all users. My aim is to make certain documents in an app "private", and I mean _really_ private, like even I as the database administrator should not be able to access them. I'm not sure if this is even possible, but thought I'd ask here. Has anyone faced a similar challenge with ShareDB? Thanks!

**Comment by alecgibson** [comment] 2023-01-09 10:31
Duplicate of https://github.com/share/sharedb/issues/211

**Closed by alecgibson** 2023-01-09 10:31 UTC
