### ISSUE TITLE
Correct way to listen to changes on several documents

### ISSUE THREAD

**Issue by yarnball** [share/sharedb#305] opened 2019-08-07 21:40 UTC
Hi, Im seeing some unexpected behaviour- but I feel I may have mis-understood the docs. 

The issue I'm seeing is that when I disconnected, it only sometimes "reconnects" - it sees the `readState` as open, but the new changes are not subscribed. It's like a need a better way to check the sockets' actual "state"...

It seems that `createSubscribeQuery` only subscribes to changes on the collection (ie adding/removing a document). It does not see changes that happen per `document` such as text changes- is that correct? 

Is the below code the correct way to connect/listen for changes (such as `op`s) on a large amount of `documents`?

Full code is here (and welcome to add this as a [Vue example](https://github.com/yarnball/shareDBdemo/blob/master/src/App.vue)). Hosted on heroku here: (https://yarnball.github.io/shareDBdemo/)

```
      const doc = connection((v)=>this.socketState = v).createSubscribeQuery(this.areaName, {})
      const _this = this
      const setRes = (data, unsubscribe) => {
        const res = connection().get(this.areaName, data.id)
        const addOrUpdate = p => _this.$set(_this.playerList, p.id, {id:p.id, ...p.data})
        res.on('op', () => {
          addOrUpdate(res)
        })
        if(!unsubscribe){
          res.subscribe(err=> {
            if (err) throw err;
            addOrUpdate(res)
          })
        }
        else{
          res.unsubscribe(err=> {
            if (err) throw err;
            _this.$delete(_this.playerList, res.id)
          })
        }
      }
      doc.on('ready', () => {
        doc.results.forEach(p=>setRes(p))
      })
      doc.on('insert', newData => {
        newData.forEach(p=>setRes(p))
      })
      doc.on('remove', removedData => {
        removedData.forEach(p=>setRes(p, true))
      })
```

(that "socketState" is just a call back I'm passing to the connection, in order to try and debug what's going on when the socket seems to stop listening)

**Comment by ericyhwang** [comment] 2019-08-08 03:12
Neat! Thanks for the live demo, made it easy to reproduce.

## Watching for changes inside of a query's docs

Subscribing to a query will automatically get you op subscriptions for all matching docs too, so you don't need the `res.subscribe(...)` and `res.unsubscribe(...)` in your example. With the debug output in the next section, you'd see that it's currently receiving ops twice, which is harmless since Share de-dupes them, but still extra data transferred.

You _do_ still need the `res.on('op', ...)` to receive notifications about changes inside each doc. With a query subscription, the Share docs' data will get updated in-memory with remote changes regardless of doc event listeners. The "op" event listener just lets you notify your app of doc changes.

## Not receiving messages after reconnect

I think the problem lies at the reconnecting-websocket layer, where the socket doesn't realize it's gotten disconnected and needs to reconnect. I haven't used it before, so I won't be of as much help in WebSocket-land.

One useful ShareDB debugging tool is to set `connection.debug = true;`, or `connection().debug = true;` in your example. That causes the ShareDB client to log out all the messages it's sending and receiving.

When it gets hung, ShareDB isn't receiving any messages from the server. Chrome's dev tools now let you inspect websocket messages, and it didn't show any messages, either.

I then tried editing an unrelated item. That op supposedly got sent out on the websocket, but there wasn't an acknowledgement back. After a couple minutes of being hung, a new websocket connection got established. The ShareDB client then successfully reconnected via the new socket, finished sending the op, and received any ops that it had missed while it was offline.

At that point, Chrome showed that the old websocket request had been stalled for several minutes. That all points to the problem being at that layer.

I noticed you were using https://github.com/joewalnes/reconnecting-websocket instead of the https://github.com/pladaria/reconnecting-websocket library that's linked from the ShareDB README, so I'd say give the latter one a try. If the issue still manifests, then I'd recommend filing an issue with reconnecting-websocket.

Good luck!

**Closed** 2019-08-08 03:13 UTC
