### ISSUE TITLE
"Document already created" error is undocumented

### ISSUE THREAD

**Issue by glor** [share/sharedb#297] opened 2019-06-11 08:20 UTC
When you call create on an already existing document you get the `Error: Invalid op submitted. Document already created` error. I did not find this error in the documentation. A quick search in the code revealed that such an error gets thrown in `lib/client/doc.js`
```javascript
return new ShareDBError(4018, 'Document alredy created');
```
The documentation instead lists `4018 - Document was created remotely`.
And if I'm already giving feedback: I generally found the documentation a little unintuitive.

**Comment by alecgibson** [comment] 2019-06-11 13:51
This issue is a duplicate of https://github.com/share/sharedb/issues/198 and https://github.com/share/sharedb/issues/294

**Closed by alecgibson** 2019-06-11 13:51 UTC
