### ISSUE TITLE
Concurrent multi-user collaboration bug related to #265

### ISSUE THREAD

**Issue by rgazelot** [share/sharedb#266] opened 2019-02-11 17:22 UTC
Hello guys,

I'm working on the issue #265 for a week now. I learned a lot from the library and I wanted to explain all the context of the issue with a bit more details:

### Testing context
All my tests was made on the [examples/rich-text](https://github.com/share/sharedb/tree/master/examples/rich-text) implementation. Here is the script used to trigger the bug:

```js
function fakeInsert (int) {
  if (int === false && window._fakeInsertTimeout) {
    clearTimeout(window._fakeInsertTimeout)
    console.log('FakeCollab STOPED!')
    return
  }

  quill.insertText(quill.getLength() - 1, Math.random().toString(36).replace(/[^a-z]+/g, '').substr(0, 1), 'user')

  window._fakeInsertTimeout = setTimeout(() => fakeInsert(), 100) // 100ms
}
```

### Scenario
I open two clients and start the `fakeInsert()` function from the console. It simulates keyboard actions instead of rolling my head very fast on it.

### How long?
After a lot of testing, I found that this concurrent multi-user collaboration issue comes from the latency of the database adapter used. The default [MemoryDB](https://github.com/share/sharedb/blob/master/lib/db/memory.js) works well! But as soon as I start using adapters, it happens. The one I'm interested in is a [Redis adapter](https://gist.github.com/rgazelot/56a512f0ced4b8876d2542d719fdd324). The issue comes randomly but usually after arround 600-1000 ops.

### State after the conflict

Here you can find the network frames of the client **A**...

```
16:01:14.242 {"a":"op","c":"examples","d":"richtext","v":703,"seq":311,"op":{"ops":[{"retain":705},{"insert":"g"}]}}
16:01:14.248 {"src":"6904c72ffd1cc9aa54d2e0b0235c02d3","seq":311,"v":703,"a":"op","c":"examples","d":"richtext"}
16:01:14.349 {"a":"op","c":"examples","d":"richtext","v":704,"seq":312,"op":{"ops":[{"retain":706},{"insert":"b"}]}}
16:01:14.377 {"a":"op","c":"examples","d":"richtext","v":704,"src":"d05203f088d08f01a06076a78755010d","seq":279,"op":{"ops":[{"retain":706},{"insert":"m"}]}}
16:01:14.421 {"src":"6904c72ffd1cc9aa54d2e0b0235c02d3","seq":312,"v":704,"a":"op","c":"examples","d":"richtext"}
16:01:14.435 {"a":"op","c":"examples","d":"richtext","v":705,"src":"d05203f088d08f01a06076a78755010d","seq":280,"op":{"ops":[{"retain":707},{"insert":"j"}]}}
16:01:14.592 {"a":"op","c":"examples","d":"richtext","v":706,"src":"d05203f088d08f01a06076a78755010d","seq":281,"op":{"ops":[{"retain":708},{"insert":"x"}]}}
```

...and the client **B**

```
16:01:14.248 {"a":"op","c":"examples","d":"richtext","v":703,"src":"6904c72ffd1cc9aa54d2e0b0235c02d3","seq":311,"op":{"ops":[{"retain":705},{"insert":"g"}]}}
16:01:14.310 {"a":"op","c":"examples","d":"richtext","v":704,"seq":279,"op":{"ops":[{"retain":706},{"insert":"m"}]}}
16:01:14.377 {"src":"d05203f088d08f01a06076a78755010d","seq":279,"v":704,"a":"op","c":"examples","d":"richtext"}
16:01:14.428 {"a":"op","c":"examples","d":"richtext","v":704,"src":"6904c72ffd1cc9aa54d2e0b0235c02d3","seq":312,"op":{"ops":[{"retain":706},{"insert":"b"}]}}
16:01:14.429 {"a":"op","c":"examples","d":"richtext","v":705,"seq":280,"op":{"ops":[{"retain":707},{"insert":"j"}]}}
16:01:14.435 {"src":"d05203f088d08f01a06076a78755010d","seq":280,"v":705,"a":"op","c":"examples","d":"richtext"}
16:01:14.535 {"a":"op","c":"examples","d":"richtext","v":706,"seq":281,"op":{"ops":[{"retain":708},{"insert":"x"}]}}
```

Here are the Redis keys:

```
127.0.0.1:6379> zrange sharedb:ops:examples:richtext 706 710
1) "{\"src\":\"6904c72ffd1cc9aa54d2e0b0235c02d3\",\"seq\":311,\"v\":703,\"op\":{\"ops\":[{\"retain\":705},{\"insert\":\"g\"}]},\"m\":{\"ts\":1549897274245}}"
2) "{\"src\":\"6904c72ffd1cc9aa54d2e0b0235c02d3\",\"seq\":312,\"v\":704,\"op\":{\"ops\":[{\"retain\":706},{\"insert\":\"b\"}]},\"m\":{\"ts\":1549897274352}}"
3) "{\"src\":\"d05203f088d08f01a06076a78755010d\",\"seq\":279,\"v\":704,\"op\":{\"ops\":[{\"retain\":706},{\"insert\":\"m\"}]},\"m\":{\"ts\":1549897274312}}"
4) "{\"src\":\"d05203f088d08f01a06076a78755010d\",\"seq\":280,\"v\":705,\"op\":{\"ops\":[{\"retain\":707},{\"insert\":\"j\"}]},\"m\":{\"ts\":1549897274431}}"
5) "{\"src\":\"d05203f088d08f01a06076a78755010d\",\"seq\":281,\"v\":706,\"op\":{\"ops\":[{\"retain\":708},{\"insert\":\"x\"}]},\"m\":{\"ts\":1549897274538}}"
```

```json
127.0.0.1:6379> get sharedb:snapshot:examples:richtext
"{\"id\":\"richtext\",\"v\":731,\"type\":\"http://sharejs.org/types/rich-text/v1\",\"data\":{\"ops\":[{\"insert\":\"Hi! adfdrayfjenfvlsectlvhakrzadffwmblieesrauvisfoqsozjsbxttdlkbgmnhhitnsibyndsrfzojfdfludhqlyxkgranwgvhgjttepcdhkrgtgzqhftlcmaylifriquwjnmrzdwqjkqkntkenyddbxjcuawjrqoaewyxzkhvgjysrslfztroauwierliifcvicqcvtpebtagmbzbudldtzchavheophvgmekdaqdklcfmzwkcxwtffovdeiwjmyuydxouzgokgtiwevdlemmulqqwhalwcrxdazfeqgajttcceqjztctvnsxglghodbnuroxieuqrxifacamwdvnxudvjoihaerqdsharlsufvomdukkmnyfclgfeeehamuweohgpnlrxxelxrivpzexbcztdkncuhgxlvxfaqskvchzcyrdyjlfcewubyxrggalfrakiohinnxtdxhxyyusfhxkmscsxgqonlauwnqggschabdbkislzzdgxvdfbgqiciiejtljvmzriqvqbawparhfhuenwcyevsgfhcnfwqejixujwrahmyaqvqmwfazvazqlfznsmxrlztnfxuusslcneypaufqyqtnbywrjvrjgmmmtgywnqtjnkohxetenbzrtpklealhtotpydtxmkkzfwxygjufxrcgdupqxrhgfrwyuetxjdkksnggbjxohhohhekvjhgxrohizmqoxwc\"}]},\"m\":{\"ctime\":1549897152142,\"mtime\":1549897277111}}"
```

### Flow
1- The `seq 312` from the client A has been sent at `16:01:14.349`
2- This client received an op from the client B at `16:01:14.377` emitted at `16:01:14.310`
3- The `seq 279` from the client B is the version 704 treated by the server at `1549897274312`
4- Then the server acknowledges the client A `seq 312` at `1549897274352`
5- Both clients receive the acknowledge. For the client B, nothing to worry about, because the version is lower than its version. This op is ignored.
6- The client A can't acknowledge its `inflightOp` because of the version mismatch.

### The bug
As the client A cannot acknowledge the message, it tries to [fetch](https://github.com/share/sharedb/blob/master/lib/client/doc.js#L846). As far as I know, it correctly fetches the snapshot from the server which is correctly applied. But the `inflightOp` is not cleaned! So the document state is in pending mode. Every new operations are put in the pending queue and never sent to the server.

### Tries
I tried to [_clearInflightOp()](https://github.com/share/sharedb/blob/master/lib/client/doc.js#L922) after the [fetch](https://github.com/share/sharedb/blob/master/lib/client/doc.js#L846) but went stuck in an incoherent state. The same with a [_hardRollback](https://github.com/share/sharedb/blob/master/lib/client/doc.js#L890)

**Comment by alecgibson** [comment] 2019-02-11 17:58
Hello! Welcome to the wonderful world of debugging ShareDB corner cases. Thanks for all of your work so far!

To continue work, I'd suggest putting together a reliably failing test case so we can try to greenify it.

Putting together tests to catch these corner cases can be very tricky, but I've had some luck [abusing the middleware][1] to attempt to force a certain sequence of events to take place.

[1]: https://github.com/share/sharedb/blob/d41e0347b4b6e6ea1e0a7d8d01bb9292e593cb1b/test/client/doc.js#L265-L343

**Comment by rgazelot** [comment] 2019-02-12 16:39
@alecgibson Thanks for your answer. I'm able to add a test to reproduce the conflict. But first, I wanted to fix my product which is all based on the Quill editor and the collaboration between users. I submitted a proposition https://github.com/share/sharedb/pull/267. Let me know what do you think about it. Best.

**Comment by alecgibson** [comment] 2019-02-12 17:45
@rgazelot the best way to continue is probably to dial in to the PR meeting tomorrow at 5pm GMT. @ericyhwang should be able to get the meeting details to you.

**Comment by rgazelot** [comment] 2019-02-13 09:30
@alecgibson Yes perfect!

**Comment by ericyhwang** [comment] 2019-02-13 16:35
Hey there, here's the link to the meeting - it'll start in a little under 30 minutes from now:

https://zoom.us/j/945699253?pwd=YzZJUXY3NkIyMnphVDM0TVBhQnhGdz09

PIN is `2697-7711` (I'll edit this out in a minute once GitHub sends you an email)

**Comment by alecgibson** [comment] 2019-02-13 16:38
(@ericyhwang NB: I personally don't have email notifications activated for my Github account - we potentially need some slightly slicker way of sharing the invite...?)

**Comment by ericyhwang** [comment] 2019-02-13 16:40
> NB: I personally don't have email notifications activated for my Github account - we potentially need some slightly slicker way of sharing the invite...?)

Good point - Perhaps a contributor Google Group might work better?

**Comment by nateps** [comment] 2019-02-13 17:29
Hey there!

Thanks for providing the detailed report, @rgazelot. Super helpful!

The first thing that stands out to me is that there are two Redis keys with the same version, 704. It is possible that the root cause of this is that the server has not properly dealt with creating sequential versions for the document. From what we can see in your Redis adapter, it doesn't look like you are rejecting the `commit` when an op at the same version already exists.

Have you been able to use share's DB test suite to test your adapter? I'd recommend looking at the tests for sharedb-mingo-memory: https://github.com/share/sharedb-mingo-memory/blob/master/test/test.js#L10. 

We'd be happy to chat more about how you can implement a Redis adapter that does an atomic check when it stores the op and makes sure the version is always unique.

**Comment by ericyhwang** [comment] 2019-02-13 17:54
Based on Nate's observation, I took a deeper look at the Redis adapter code. In [the adapter's `_addOps`](https://gist.github.com/rgazelot/56a512f0ced4b8876d2542d719fdd324#file-redis-js-L43), it does a `zadd(`sharedb:ops:${collection}:${id}`, op.v || 0, JSON.stringify(op)`.

So that could result in an op with a duplicate version.

Unfortunately, reading the [ZADD docs](https://redis.io/commands/zadd), I don't see any built-in way to return an error when trying to add another element with the same score. The `NX` option is based on the member's value, which is different for ops with different content.

One option is to use [Redis `EVAL`](https://redis.io/commands/eval) to atomically:
* Check if there's an existing op of the version (score) it's trying to commit, and return an error if that's true
* Then do the `ZADD` only if there is not an existing op of that version

As an example, the Redis-based pubsub adapter for ShareDB uses `EVAL`:

https://github.com/share/sharedb-redis-pubsub/blob/v1.0.0-beta.1/index.js#L61

**Comment by rgazelot** [comment] 2019-02-14 17:29
Thanks both of you for insights and the time you took to understand the described behavior. I'm totally new to the ShareDB and OT transformations but after two weeks of trying to solve our editor issues, I start to see the little light at the end of the tunnel.

I understand your observations about our Redis Adapter and the `commit()` method. When I look at the Postegre Adapter, [it rejects](https://github.com/share/sharedb-postgres/blob/master/index.js#L67) the `op` if the snapshot version is different than the `max_version + 1` in the ops database. So I implemented the same behavior for the Redis Adapter. 

After some tests, I always fall inside an infinite loop of retries because of this test. Actually I don't understand how this could work for the Postegre Adapter. Suppose your max version is `0`, the initial commit created with a `CreateOp`. Your stored snapshot will be at the version `1`. 

```
127.0.0.1:6379> zrange sharedb:ops:examples:richtext 0 -1 withscores
1) "{\"src\":\"2fcfd35cfbbd713e9524523c7b43e394\",\"seq\":1,\"v\":0,\"create\":{\"type\":\"http://sharejs.org/types/rich-text/v1\",\"data\":[{\"insert\":\"Hi!\"}]},\"m\":{\"ts\":1550163933459}}"
2) "0"
```

```
127.0.0.1:6379> get sharedb:snapshot:examples:richtext
"{\"id\":\"richtext\",\"v\":1,\"type\":\"http://sharejs.org/types/rich-text/v1\",\"data\":{\"ops\":[{\"insert\":\"Hi!\"}]},\"m\":{\"ctime\":1550163933459,\"mtime\":1550163933459}}"
```

When the client send an `EditOp` for the version `1`, the linked test cannot work and the `callback()` is called with the `succeed` argument to false which lead us to an infinite loop of retries.

By the way, I used a `zrangebyscore` in order to be sure to never store an element into the sorted set with a duplicated `score`, as the `versions` are the `scores` of the sorted set. This works wells after some tests. When two clients send the same version, one is persisted, the other one is retry and persisted with an updated (+1) version. I will be able to show you an updated version of the Redis Adapter Gist tomorrow.

Thanks again for your help and your time guys. Your work is the main base of our product and it'll be a pleasure for us to contribute and offer a very efficient way to use ShareDb with a Redis Adapter.

**Comment by rgazelot** [comment] 2019-02-15 17:37
Hello, below you'll find the new `commit()` method for the Redis adapter.

```
commit (collection, id, op, snapshot, options, callback) {
      // Watch the key sharedb:snapshot to be sure that nothing will change
      // between the check-and-set
      // @see https://redis.io/topics/transactions#optimistic-locking-using-check-and-set
      this.client.watch(`sharedb:snapshot:${collection}:${id}`, function (err) {
        if (err) return callback(err);

        // Find if there is already an op in the sorted set with the op's version
        this.client.zrangebyscore(`sharedb:ops:${collection}:${id}`, op.v, op.v, function (err, res) {
          if (err) return callback(err);

          // An op has been find. Let's retry the commit using the callback
          if (0 < res.length) {
            return callback(null, false)
          }

          // Retrieve the highest ops version of the collection
          this.client.zrevrangebyscore(`sharedb:ops:${collection}:${id}`, '+inf', 0, 'withscores', 'limit', 0, 1, function (err, res) {
            if (err) return callback(err);

            let version = 0

            if (res && res[1]) {
              version = parseInt(res[1])
            }

            // @see https://github.com/share/sharedb-postgres/blob/master/index.js#L67
            if (snapshot.v !== version + 1) {
              return callback(null, false);
            }

            // Call in a single transaction the following set commands
            this.client.multi()
              .zadd(`sharedb:ops:${collection}:${id}`, op.v || 0, JSON.stringify(op))
              .set(`sharedb:snapshot:${collection}:${id}`, JSON.stringify(snapshot), 'EX', this.ttl)
              .exec(function (err, res) {
                if (err) return callback(err);

                // The watched key changed, the commit has to be aborted and retried
                if (null === res) return callback(null, false);

                // Everything went fine
                return callback(null, true);
              });
          }.bind(this));
        }.bind(this));
      }.bind(this));
    }
```

I tried to use the WATCH and MULTI EXEC commands of Redis in order to be sure that nothing changed between the `zrangebyscore` and the `zadd` which could lead to have multiple ops with the same score into the ops sorted set. 

This works well above the pace of a request every 150ms. Below this pace, it is possible to have a race condition where the WATCH doesn't seem to work fine. Using the MONITOR command, I was able to know what happened under the wood:

![screen shot 2019-02-15 at 6 02 31 pm](https://user-images.githubusercontent.com/1488251/52873566-9d22ed00-314f-11e9-879d-d07cd4a86e60.png)

I still don't know if the WATCH command has a limitation or if I did something wrong. But I feel close to have something stronger.

**Comment by ericyhwang** [comment] 2019-02-15 22:39
I haven't used WATCH before, but skimming the docs on transactions, specifically [the section on WATCH](https://redis.io/topics/transactions#a-hrefcommandswatchwatcha-explained), one thing jumped out at me:

> So what is WATCH really about? It is a command that will make the EXEC conditional: we are asking Redis to perform the transaction only if none of the WATCHed keys were modified. (But they **might be changed by the same client** inside the transaction without aborting it. More on this.)

Emphasis mine. Since the adapter uses a single Redis client, means multiple requests could interleave WATCH on a single Redis client, which the Redis logs above seem to show. I did a bit of searching and found this, about the trickiness of using WATCH from Node.js: https://github.com/luin/ioredis/issues/266

Using EVAL with a Lua script like sharedb-redis-pubsub won't run into that issue, as the script and parameters are sent to Redis to execute as a unit. So that's probably what I'd choose to use given the context you've shared.

**Comment by rgazelot** [comment] 2019-02-18 14:20
Hello guys, hope you had a great weekend. Here you can find the `commit()` method of the Redis adapter according to the eval usage:

```
commit (collection, id, op, snapshot, options, callback) {
      const script = `
        local op = redis.call("zrangebyscore", KEYS[1], ARGV[1], ARGV[1])

        -- If a version (score) already exists, do not duplicate it
        if #op ~= 0
        then
          return redis.status_reply("Duplicated score")
        end

        -- Add the op to the collection
        redis.call("zadd", KEYS[1], ARGV[1], ARGV[2])

        -- Refresh the expire of the ops collection
        redis.call("expire", KEYS[1], ARGV[4])

        -- Save the snapshot
        redis.call("set", KEYS[2], ARGV[3], "EX", ARGV[4])

        return redis.status_reply("OK")
      `;

      this.client.eval(
        script, // The lua script above
        2, // The following 2 keys
        `sharedb:ops:${collection}:${id}`, // KEYS[1] Ops collection key
        `sharedb:snapshot:${collection}:${id}`, // KEYS[2] Snapshot key
        op.v || 0, // ARGV[1] The op version (special case for the create)
        JSON.stringify(op), // ARGV[2] The op
        JSON.stringify(snapshot), // ARGV[3] The snapshot
        this.ttl, // ARGV[4] The TTL to apply to all the keys
        function (err, res) {
          if (err) return callback(err)

          if (res === 'Duplicated score') {
            return callback(null, false)
          }

          if (res === 'OK') ? callback(null, true) : return callback(err)
        }
      );
    }
```
*This  works very well!*
For the testing, I used two clients who sent op every 200-150ms. Conflicts are correctly handle according to some logs added into the eval's callback method:

``` 
commit 1320 [ { retain: 1397 }, { insert: 'C' } ]
commit 1320 [ { retain: 1397 }, { insert: 'K' } ]
OK 1320 [ { retain: 1397 }, { insert: 'C' } ]
duplicated score 1320 Duplicated score
commit 1321 [ { retain: 1398 }, { insert: 'K' } ]
OK 1321 [ { retain: 1398 }, { insert: 'K' } ]
```

The `K` is correctly rejected and commited at the next version. 

*Final question*: Do I have to check the Max Version in my ops collection and compare it to the current one? This is a question related to [my previous comment](https://github.com/share/sharedb/issues/266#issuecomment-463716435) about the Postegre adapter.

If you guys like the way the `commit()` method works, It'll be my pleasure to create a repository and properly expose the Redis Adapter standalone.

**Comment by rgazelot** [comment] 2019-02-26 13:29
Hi guys, all this work is in production on our product and after some tests it works well. What are your thoughts about it? Is a Redis Adapter is something you're interested in?

**Comment by ericyhwang** [comment] 2019-02-28 02:06
Glad it's working out for you!

We discussed during the weekly contributor meeting today. Since you've written all the Redis DB adapter code and are using it in production, we've decided that at the moment, it makes the most sense for you to act as the maintainer, if you're willing to do so.

Here's what's left to do:

1. Try running `sharedb`'s DB integration tests using the Redis DB adapter, and fix any issues
    * To do this, install `sharedb` as a `devDependency` in `sharedb-redis`, then have it include the DB tests.
    * As an example, see [how sharedb-mongo does it](https://github.com/share/sharedb-mongo/blob/v1.0.0-beta.8/test/test_mongo.js#L8-L21).
    * The `getQuery` function maps the Share query syntax to the adapter DB's query syntax. Looks like the current sharedb-redis doesn't implement `db.query()`, so you can ignore `getQuery` for now.
    * When you run the tests, you can run with `mocha --grep '[Qq]uery' --invert` to ignore the query tests.
2. Open-source the adapter under your company's org
    * Everything under the Share org uses the [MIT license](https://opensource.org/licenses/MIT), but feel free to use another permissive license like Apache if you'd like.
    * I'd recommend calling the repo `sharedb-redis`, to match the naming convention of existing adapters.
3. Publish to NPM
    * It'd be a good idea to note in the README that queries are unsupported.

Let us know if you have any questions!

----

Answering your question from above:

> **Final question**: Do I have to check the Max Version in my ops collection and compare it to the current one? This is a question related to [my previous comment](https://github.com/share/sharedb/issues/266#issuecomment-463716435) about the Postegre adapter.

Yeah, you should do that max version check for both [the op](https://github.com/share/sharedb-postgres/blob/65faa530d462c5ba06779abad1ed7459c0f9764d/index.js#L67) and [the snapshot](https://github.com/share/sharedb-postgres/blob/65faa530d462c5ba06779abad1ed7459c0f9764d/index.js#L100) up front in the Lua script, before making any changes. It's important to check up front in the Lua script, since it doesn't have the same rollback properties of a DB transaction, which is what sharedb-postgres relies on.

**Comment by rgazelot** [comment] 2019-03-12 09:23
Hi @ericyhwang, glad to see that our work can be used as the main Redis DB adapter. We're willing to be the maintainers of this repository. Keep in touch on this repository and thanks for your help and your good work on sharedb. 
Best,
The Wisembly Team

**Comment by curran** [comment] 2019-04-18 06:42
Suggest to close this as it's been resolved (original bug was external to ShareDB, not clear if there's a problem with ShareDB itself around this discussion).

**Closed** 2019-04-18 07:52 UTC
