### ISSUE TITLE
Does sharedb Mongo support double write databases?

### ISSUE THREAD

**Issue by tuluffy** [share/sharedb#554] opened 2022-03-17 10:30 UTC
For example, one database performs OP persistence (old OPS will be deleted at intervals), and the other database records all OPS (for behavior analysis). thx!

**Comment by curran** [comment] 2022-03-17 13:24
Recommend to close as duplicate of https://github.com/share/sharedb-mongo/issues/125

**Comment by ericyhwang** [comment] 2022-04-05 16:07
Closing as duplicate as Curran mentions above

**Closed by ericyhwang** 2022-04-05 16:07 UTC
